# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23

minecraft_version=1.21.4
minecraft_version_range=[1.21.4, 1.22)
neo_version=21.4.156
neo_version_range=[21.3.0,)
loader_version_range=[4,)

neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23

# Mod Properties
mod_id=instrumentus
mod_name=Instrumentus
mod_license=MIT

mod_version=1.21.4-2.8.7

mod_group_id=com.beanbot.instrumentus
mod_authors=Beanxxbot
mod_description=Instrumentus features many different tools that fall under many different content categories! Some examples include Paxels, AOE Tools, Sickles, More Brushes, and many more.

jei_version=20.0.0.4
jade_version=17.3.0+neoforge

# https://modrinth.com/mod/curios/versions
curios_version=10.0.1

# https://maven.createmod.net/net/createmod/ponder/
ponder_version=1.0.81

# https://maven.createmod.net/dev/engine-room/flywheel/
flywheel_version=1.0.5-32
flywheel_version_range=[1.0.0,2.0)

# https://maven.createmod.net/com/simibubi/create/create-1.21.1/
create_version=6.0.9-201

registrate_version=MC1.21-1.3.0+67